name = "fascinante-api-gateway-prod"
main = "src/index.ts"
compatibility_date = "2025-10-27"
compatibility_flags = ["nodejs_compat"]

# KV Namespaces para contexto automatizado
[[kv_namespaces]]
binding = "CONTEXT_KV"
id = "8e325322533443059fa7b0c208d7f5fb"
preview_id = "627e60ab23fb4aa5a0a1f9f1ccc79d39"

# Cron Triggers para actualización automática de contexto
[triggers]
crons = ["0 */6 * * *"] # Cada 6 horas

# Environment variables
[env.production]
name = "fascinante-api-gateway-prod"
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"
CONTEXT_API_URL = "https://api.fascinantedigital.com"
# Next.js: solo releases (no hay RSS oficial del blog)
NEXTJS_RELEASES = "https://api.github.com/repos/vercel/next.js/releases"
# Supabase: releases
SUPABASE_RELEASES = "https://api.github.com/repos/supabase/supabase/releases"
# Cloudflare: RSS oficial del Changelog
CLOUDFLARE_CHANGELOG_RSS = "https://developers.cloudflare.com/changelog/rss/index.xml"
# RESEND_API_KEY se configura como secret (no en el archivo)

# KV Namespaces para production
[[env.production.kv_namespaces]]
binding = "CONTEXT_KV"
id = "8e325322533443059fa7b0c208d7f5fb"

# Cron Triggers para production
[env.production.triggers]
crons = ["0 */6 * * *"] # Cada 6 horas

[env.staging]
name = "fd-api-gateway-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
API_VERSION = "1.0.0-staging"
CONTEXT_API_URL = "https://staging-api.fascinantedigital.com"

# Variables para contexto automatizado (ambos entornos)
[vars]
# Next.js: solo releases (no hay RSS oficial del blog)
NEXTJS_RELEASES = "https://api.github.com/repos/vercel/next.js/releases"
# Supabase: releases
SUPABASE_RELEASES = "https://api.github.com/repos/supabase/supabase/releases"
# Cloudflare: RSS oficial del Changelog
CLOUDFLARE_CHANGELOG_RSS = "https://developers.cloudflare.com/changelog/rss/index.xml"
