name = "fascinante-api-gateway-prod"
main = "src/index.ts"
compatibility_date = "2025-10-27"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[env.production]
name = "fascinante-api-gateway-prod"
[env.production.vars]
ENVIRONMENT = "production"
API_VERSION = "1.0.0"

[env.staging]
name = "fascinante-api-staging"
[env.staging.vars]
ENVIRONMENT = "staging"
API_VERSION = "1.0.0-staging"
